package com.cornerstones.models;

/*
 * PARTY Entity Catalog=ofbiz
 */

//Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
* Party generated by hbm2java
*/
@Entity
@Table(name = "PARTY", catalog = "ofbiz")
public class Party implements java.io.Serializable {

	private String partyId;
	private String partyTypeId;
	private String externalId;
	private String preferredCurrencyUomId;
	private String description;
	private String statusId;
	private Date createdDate;
	private String createdByUserLogin;
	private Date lastModifiedDate;
	private String lastModifiedByUserLogin;
	private String dataSourceId;
	private Character isUnread;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public Party() {
	}

	public Party(String partyId) {
		this.partyId = partyId;
	}

	public Party(String partyId, String partyTypeId, String externalId, String preferredCurrencyUomId,
			String description, String statusId, Date createdDate, String createdByUserLogin, Date lastModifiedDate,
			String lastModifiedByUserLogin, String dataSourceId, Character isUnread, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.partyId = partyId;
		this.partyTypeId = partyTypeId;
		this.externalId = externalId;
		this.preferredCurrencyUomId = preferredCurrencyUomId;
		this.description = description;
		this.statusId = statusId;
		this.createdDate = createdDate;
		this.createdByUserLogin = createdByUserLogin;
		this.lastModifiedDate = lastModifiedDate;
		this.lastModifiedByUserLogin = lastModifiedByUserLogin;
		this.dataSourceId = dataSourceId;
		this.isUnread = isUnread;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@Id

	@Column(name = "PARTY_ID", unique = true, nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "PARTY_TYPE_ID", length = 20)
	public String getPartyTypeId() {
		return this.partyTypeId;
	}

	public void setPartyTypeId(String partyTypeId) {
		this.partyTypeId = partyTypeId;
	}

	@Column(name = "EXTERNAL_ID", length = 20)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	@Column(name = "PREFERRED_CURRENCY_UOM_ID", length = 20)
	public String getPreferredCurrencyUomId() {
		return this.preferredCurrencyUomId;
	}

	public void setPreferredCurrencyUomId(String preferredCurrencyUomId) {
		this.preferredCurrencyUomId = preferredCurrencyUomId;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "STATUS_ID", length = 20)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CREATED_BY_USER_LOGIN", length = 250)
	public String getCreatedByUserLogin() {
		return this.createdByUserLogin;
	}

	public void setCreatedByUserLogin(String createdByUserLogin) {
		this.createdByUserLogin = createdByUserLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_MODIFIED_DATE", length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Column(name = "LAST_MODIFIED_BY_USER_LOGIN", length = 250)
	public String getLastModifiedByUserLogin() {
		return this.lastModifiedByUserLogin;
	}

	public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
		this.lastModifiedByUserLogin = lastModifiedByUserLogin;
	}

	@Column(name = "DATA_SOURCE_ID", length = 20)
	public String getDataSourceId() {
		return this.dataSourceId;
	}

	public void setDataSourceId(String dataSourceId) {
		this.dataSourceId = dataSourceId;
	}

	@Column(name = "IS_UNREAD", length = 1)
	public Character getIsUnread() {
		return this.isUnread;
	}

	public void setIsUnread(Character isUnread) {
		this.isUnread = isUnread;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
