package com.cornerstones.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserLoginHistoryId generated by hbm2java
 */
@Embeddable
public class UserLoginHistoryId implements java.io.Serializable {

	private String userLoginId;
	private Date fromDate;

	public UserLoginHistoryId() {
	}

	public UserLoginHistoryId(String userLoginId, Date fromDate) {
		this.userLoginId = userLoginId;
		this.fromDate = fromDate;
	}

	@Column(name = "USER_LOGIN_ID", nullable = false, length = 250)
	public String getUserLoginId() {
		return this.userLoginId;
	}

	public void setUserLoginId(String userLoginId) {
		this.userLoginId = userLoginId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserLoginHistoryId))
			return false;
		UserLoginHistoryId castOther = (UserLoginHistoryId) other;

		return ((this.getUserLoginId() == castOther.getUserLoginId()) || (this.getUserLoginId() != null
				&& castOther.getUserLoginId() != null && this.getUserLoginId().equals(castOther.getUserLoginId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserLoginId() == null ? 0 : this.getUserLoginId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
