package com.cornerstones.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLoginHistory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USER_LOGIN_HISTORY", catalog = "ofbiz")
public class UserLoginHistory implements java.io.Serializable {
  
	private UserLoginHistoryId id;
	private String visitId;
	private Date thruDate;
	private String passwordUsed;
	private Character successfulLogin;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;
	private String partyId;

	public UserLoginHistory() {
	}

	public UserLoginHistory(UserLoginHistoryId id) {
		this.id = id;
	}

	public UserLoginHistory(UserLoginHistoryId id, String visitId, Date thruDate, String passwordUsed,
			Character successfulLogin, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp, String partyId) {
		this.id = id;
		this.visitId = visitId;
		this.thruDate = thruDate;
		this.passwordUsed = passwordUsed;
		this.successfulLogin = successfulLogin;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
		this.partyId = partyId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userLoginId", column = @Column(name = "USER_LOGIN_ID", nullable = false, length = 250) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 19) ) })
	public UserLoginHistoryId getId() {
		return this.id;
	}

	public void setId(UserLoginHistoryId id) {
		this.id = id;
	}

	@Column(name = "VISIT_ID", length = 20)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THRU_DATE", length = 19)
	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	@Column(name = "PASSWORD_USED")
	public String getPasswordUsed() {
		return this.passwordUsed;
	}

	public void setPasswordUsed(String passwordUsed) {
		this.passwordUsed = passwordUsed;
	}

	@Column(name = "SUCCESSFUL_LOGIN", length = 1)
	public Character getSuccessfulLogin() {
		return this.successfulLogin;
	}

	public void setSuccessfulLogin(Character successfulLogin) {
		this.successfulLogin = successfulLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

	@Column(name = "PARTY_ID", length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

}
