package com.cornerstones.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserLoginPasswordHistory generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "user_login_password_history", catalog = "ofbiz")
public class UserLoginPasswordHistory implements java.io.Serializable {

	private UserLoginPasswordHistoryId id;
	private Date thruDate;
	private String currentPassword;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;
	private String userLoginIn;

	public UserLoginPasswordHistory() {
	}

	public UserLoginPasswordHistory(UserLoginPasswordHistoryId id, String userLoginIn) {
		this.id = id;
		this.userLoginIn = userLoginIn;
	}

	public UserLoginPasswordHistory(UserLoginPasswordHistoryId id, Date thruDate, String currentPassword,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp,
			String userLoginIn) {
		this.id = id;
		this.thruDate = thruDate;
		this.currentPassword = currentPassword;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
		this.userLoginIn = userLoginIn;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userLoginId", column = @Column(name = "USER_LOGIN_ID", nullable = false, length = 250) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 19) ) })
	public UserLoginPasswordHistoryId getId() {
		return this.id;
	}

	public void setId(UserLoginPasswordHistoryId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THRU_DATE", length = 19)
	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	@Column(name = "CURRENT_PASSWORD", length = 60)
	public String getCurrentPassword() {
		return this.currentPassword;
	}

	public void setCurrentPassword(String currentPassword) {
		this.currentPassword = currentPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

	@Column(name = "user_login_in", nullable = false)
	public String getUserLoginIn() {
		return this.userLoginIn;
	}

	public void setUserLoginIn(String userLoginIn) {
		this.userLoginIn = userLoginIn;
	}

}
