package com.cornerstones.agreements.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgreementTypeAttrId generated by hbm2java
 */
@Embeddable
public class AgreementTypeAttrId implements java.io.Serializable {

	private String agreementTypeId;
	private String attrName;

	public AgreementTypeAttrId() {
	}

	public AgreementTypeAttrId(String agreementTypeId, String attrName) {
		this.agreementTypeId = agreementTypeId;
		this.attrName = attrName;
	}

	@Column(name = "AGREEMENT_TYPE_ID", nullable = false, length = 20)
	public String getAgreementTypeId() {
		return this.agreementTypeId;
	}

	public void setAgreementTypeId(String agreementTypeId) {
		this.agreementTypeId = agreementTypeId;
	}

	@Column(name = "ATTR_NAME", nullable = false, length = 60)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgreementTypeAttrId))
			return false;
		AgreementTypeAttrId castOther = (AgreementTypeAttrId) other;

		return ((this.getAgreementTypeId() == castOther.getAgreementTypeId())
				|| (this.getAgreementTypeId() != null && castOther.getAgreementTypeId() != null
						&& this.getAgreementTypeId().equals(castOther.getAgreementTypeId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this.getAttrName() != null
						&& castOther.getAttrName() != null && this.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAgreementTypeId() == null ? 0 : this.getAgreementTypeId().hashCode());
		result = 37 * result + (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}
