package com.cornerstones.agreements.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgreementTerm generated by hbm2java
 */
@Entity
@Table(name = "AGREEMENT_TERM", catalog = "ofbiz")
public class AgreementTerm implements java.io.Serializable {

	private String agreementTermId;
	private String termTypeId;
	private String agreementId;
	private String agreementItemSeqId;
	private String invoiceItemTypeId;
	private Date fromDate;
	private Date thruDate;
	private BigDecimal termValue;
	private BigDecimal termDays;
	private String textValue;
	private Double minQuantity;
	private Double maxQuantity;
	private String description;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public AgreementTerm() {
	}

	public AgreementTerm(String agreementTermId) {
		this.agreementTermId = agreementTermId;
	}

	public AgreementTerm(String agreementTermId, String termTypeId, String agreementId, String agreementItemSeqId,
			String invoiceItemTypeId, Date fromDate, Date thruDate, BigDecimal termValue, BigDecimal termDays,
			String textValue, Double minQuantity, Double maxQuantity, String description, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.agreementTermId = agreementTermId;
		this.termTypeId = termTypeId;
		this.agreementId = agreementId;
		this.agreementItemSeqId = agreementItemSeqId;
		this.invoiceItemTypeId = invoiceItemTypeId;
		this.fromDate = fromDate;
		this.thruDate = thruDate;
		this.termValue = termValue;
		this.termDays = termDays;
		this.textValue = textValue;
		this.minQuantity = minQuantity;
		this.maxQuantity = maxQuantity;
		this.description = description;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@Id

	@Column(name = "AGREEMENT_TERM_ID", unique = true, nullable = false, length = 20)
	public String getAgreementTermId() {
		return this.agreementTermId;
	}

	public void setAgreementTermId(String agreementTermId) {
		this.agreementTermId = agreementTermId;
	}

	@Column(name = "TERM_TYPE_ID", length = 20)
	public String getTermTypeId() {
		return this.termTypeId;
	}

	public void setTermTypeId(String termTypeId) {
		this.termTypeId = termTypeId;
	}

	@Column(name = "AGREEMENT_ID", length = 20)
	public String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(String agreementId) {
		this.agreementId = agreementId;
	}

	@Column(name = "AGREEMENT_ITEM_SEQ_ID", length = 20)
	public String getAgreementItemSeqId() {
		return this.agreementItemSeqId;
	}

	public void setAgreementItemSeqId(String agreementItemSeqId) {
		this.agreementItemSeqId = agreementItemSeqId;
	}

	@Column(name = "INVOICE_ITEM_TYPE_ID", length = 20)
	public String getInvoiceItemTypeId() {
		return this.invoiceItemTypeId;
	}

	public void setInvoiceItemTypeId(String invoiceItemTypeId) {
		this.invoiceItemTypeId = invoiceItemTypeId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FROM_DATE", length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THRU_DATE", length = 19)
	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	@Column(name = "TERM_VALUE", precision = 18, scale = 3)
	public BigDecimal getTermValue() {
		return this.termValue;
	}

	public void setTermValue(BigDecimal termValue) {
		this.termValue = termValue;
	}

	@Column(name = "TERM_DAYS", precision = 20, scale = 0)
	public BigDecimal getTermDays() {
		return this.termDays;
	}

	public void setTermDays(BigDecimal termDays) {
		this.termDays = termDays;
	}

	@Column(name = "TEXT_VALUE")
	public String getTextValue() {
		return this.textValue;
	}

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

	@Column(name = "MIN_QUANTITY", precision = 22, scale = 0)
	public Double getMinQuantity() {
		return this.minQuantity;
	}

	public void setMinQuantity(Double minQuantity) {
		this.minQuantity = minQuantity;
	}

	@Column(name = "MAX_QUANTITY", precision = 22, scale = 0)
	public Double getMaxQuantity() {
		return this.maxQuantity;
	}

	public void setMaxQuantity(Double maxQuantity) {
		this.maxQuantity = maxQuantity;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
