package com.cornerstones.agreements.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgreementItem generated by hbm2java
 */
@Entity
@Table(name = "AGREEMENT_ITEM", catalog = "ofbiz")
public class AgreementItem implements java.io.Serializable {

	private AgreementItemId id;
	private String agreementItemTypeId;
	private String currencyUomId;
	private String agreementText;
	private byte[] agreementImage;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public AgreementItem() {
	}

	public AgreementItem(AgreementItemId id) {
		this.id = id;
	}

	public AgreementItem(AgreementItemId id, String agreementItemTypeId, String currencyUomId, String agreementText,
			byte[] agreementImage, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.agreementItemTypeId = agreementItemTypeId;
		this.currencyUomId = currencyUomId;
		this.agreementText = agreementText;
		this.agreementImage = agreementImage;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "agreementId", column = @Column(name = "AGREEMENT_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "agreementItemSeqId", column = @Column(name = "AGREEMENT_ITEM_SEQ_ID", nullable = false, length = 20) ) })
	public AgreementItemId getId() {
		return this.id;
	}

	public void setId(AgreementItemId id) {
		this.id = id;
	}

	@Column(name = "AGREEMENT_ITEM_TYPE_ID", length = 20)
	public String getAgreementItemTypeId() {
		return this.agreementItemTypeId;
	}

	public void setAgreementItemTypeId(String agreementItemTypeId) {
		this.agreementItemTypeId = agreementItemTypeId;
	}

	@Column(name = "CURRENCY_UOM_ID", length = 20)
	public String getCurrencyUomId() {
		return this.currencyUomId;
	}

	public void setCurrencyUomId(String currencyUomId) {
		this.currencyUomId = currencyUomId;
	}

	@Column(name = "AGREEMENT_TEXT")
	public String getAgreementText() {
		return this.agreementText;
	}

	public void setAgreementText(String agreementText) {
		this.agreementText = agreementText;
	}

	@Column(name = "AGREEMENT_IMAGE")
	public byte[] getAgreementImage() {
		return this.agreementImage;
	}

	public void setAgreementImage(byte[] agreementImage) {
		this.agreementImage = agreementImage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
