package com.cornerstones.agreements.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgreementTermAttributeId generated by hbm2java
 */
@Embeddable
public class AgreementTermAttributeId implements java.io.Serializable {

	private String agreementTermId;
	private String attrName;

	public AgreementTermAttributeId() {
	}

	public AgreementTermAttributeId(String agreementTermId, String attrName) {
		this.agreementTermId = agreementTermId;
		this.attrName = attrName;
	}

	@Column(name = "AGREEMENT_TERM_ID", nullable = false, length = 20)
	public String getAgreementTermId() {
		return this.agreementTermId;
	}

	public void setAgreementTermId(String agreementTermId) {
		this.agreementTermId = agreementTermId;
	}

	@Column(name = "ATTR_NAME", nullable = false, length = 60)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgreementTermAttributeId))
			return false;
		AgreementTermAttributeId castOther = (AgreementTermAttributeId) other;

		return ((this.getAgreementTermId() == castOther.getAgreementTermId())
				|| (this.getAgreementTermId() != null && castOther.getAgreementTermId() != null
						&& this.getAgreementTermId().equals(castOther.getAgreementTermId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this.getAttrName() != null
						&& castOther.getAttrName() != null && this.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAgreementTermId() == null ? 0 : this.getAgreementTermId().hashCode());
		result = 37 * result + (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}
