package com.cornerstones.agreements.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgreementRoleId generated by hbm2java
 */
@Embeddable
public class AgreementRoleId implements java.io.Serializable {

	private String agreementId;
	private String partyId;
	private String roleTypeId;

	public AgreementRoleId() {
	}

	public AgreementRoleId(String agreementId, String partyId, String roleTypeId) {
		this.agreementId = agreementId;
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
	}

	@Column(name = "AGREEMENT_ID", nullable = false, length = 20)
	public String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(String agreementId) {
		this.agreementId = agreementId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "ROLE_TYPE_ID", nullable = false, length = 20)
	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgreementRoleId))
			return false;
		AgreementRoleId castOther = (AgreementRoleId) other;

		return ((this.getAgreementId() == castOther.getAgreementId()) || (this.getAgreementId() != null
				&& castOther.getAgreementId() != null && this.getAgreementId().equals(castOther.getAgreementId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId())
						|| (this.getRoleTypeId() != null && castOther.getRoleTypeId() != null
								&& this.getRoleTypeId().equals(castOther.getRoleTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAgreementId() == null ? 0 : this.getAgreementId().hashCode());
		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getRoleTypeId() == null ? 0 : this.getRoleTypeId().hashCode());
		return result;
	}

}
