package com.cornerstones.agreements.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AgreementEmploymentApplId generated by hbm2java
 */
@Embeddable
public class AgreementEmploymentApplId implements java.io.Serializable {

	private String agreementId;
	private String agreementItemSeqId;
	private String partyIdTo;
	private String partyIdFrom;
	private String roleTypeIdTo;
	private String roleTypeIdFrom;
	private Date fromDate;

	public AgreementEmploymentApplId() {
	}

	public AgreementEmploymentApplId(String agreementId, String agreementItemSeqId, String partyIdTo,
			String partyIdFrom, String roleTypeIdTo, String roleTypeIdFrom, Date fromDate) {
		this.agreementId = agreementId;
		this.agreementItemSeqId = agreementItemSeqId;
		this.partyIdTo = partyIdTo;
		this.partyIdFrom = partyIdFrom;
		this.roleTypeIdTo = roleTypeIdTo;
		this.roleTypeIdFrom = roleTypeIdFrom;
		this.fromDate = fromDate;
	}

	@Column(name = "AGREEMENT_ID", nullable = false, length = 20)
	public String getAgreementId() {
		return this.agreementId;
	}

	public void setAgreementId(String agreementId) {
		this.agreementId = agreementId;
	}

	@Column(name = "AGREEMENT_ITEM_SEQ_ID", nullable = false, length = 20)
	public String getAgreementItemSeqId() {
		return this.agreementItemSeqId;
	}

	public void setAgreementItemSeqId(String agreementItemSeqId) {
		this.agreementItemSeqId = agreementItemSeqId;
	}

	@Column(name = "PARTY_ID_TO", nullable = false, length = 20)
	public String getPartyIdTo() {
		return this.partyIdTo;
	}

	public void setPartyIdTo(String partyIdTo) {
		this.partyIdTo = partyIdTo;
	}

	@Column(name = "PARTY_ID_FROM", nullable = false, length = 20)
	public String getPartyIdFrom() {
		return this.partyIdFrom;
	}

	public void setPartyIdFrom(String partyIdFrom) {
		this.partyIdFrom = partyIdFrom;
	}

	@Column(name = "ROLE_TYPE_ID_TO", nullable = false, length = 20)
	public String getRoleTypeIdTo() {
		return this.roleTypeIdTo;
	}

	public void setRoleTypeIdTo(String roleTypeIdTo) {
		this.roleTypeIdTo = roleTypeIdTo;
	}

	@Column(name = "ROLE_TYPE_ID_FROM", nullable = false, length = 20)
	public String getRoleTypeIdFrom() {
		return this.roleTypeIdFrom;
	}

	public void setRoleTypeIdFrom(String roleTypeIdFrom) {
		this.roleTypeIdFrom = roleTypeIdFrom;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AgreementEmploymentApplId))
			return false;
		AgreementEmploymentApplId castOther = (AgreementEmploymentApplId) other;

		return ((this.getAgreementId() == castOther.getAgreementId()) || (this.getAgreementId() != null
				&& castOther.getAgreementId() != null && this.getAgreementId().equals(castOther.getAgreementId())))
				&& ((this.getAgreementItemSeqId() == castOther.getAgreementItemSeqId())
						|| (this.getAgreementItemSeqId() != null && castOther.getAgreementItemSeqId() != null
								&& this.getAgreementItemSeqId().equals(castOther.getAgreementItemSeqId())))
				&& ((this.getPartyIdTo() == castOther.getPartyIdTo()) || (this.getPartyIdTo() != null
						&& castOther.getPartyIdTo() != null && this.getPartyIdTo().equals(castOther.getPartyIdTo())))
				&& ((this.getPartyIdFrom() == castOther.getPartyIdFrom())
						|| (this.getPartyIdFrom() != null && castOther.getPartyIdFrom() != null
								&& this.getPartyIdFrom().equals(castOther.getPartyIdFrom())))
				&& ((this.getRoleTypeIdTo() == castOther.getRoleTypeIdTo())
						|| (this.getRoleTypeIdTo() != null && castOther.getRoleTypeIdTo() != null
								&& this.getRoleTypeIdTo().equals(castOther.getRoleTypeIdTo())))
				&& ((this.getRoleTypeIdFrom() == castOther.getRoleTypeIdFrom())
						|| (this.getRoleTypeIdFrom() != null && castOther.getRoleTypeIdFrom() != null
								&& this.getRoleTypeIdFrom().equals(castOther.getRoleTypeIdFrom())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAgreementId() == null ? 0 : this.getAgreementId().hashCode());
		result = 37 * result + (getAgreementItemSeqId() == null ? 0 : this.getAgreementItemSeqId().hashCode());
		result = 37 * result + (getPartyIdTo() == null ? 0 : this.getPartyIdTo().hashCode());
		result = 37 * result + (getPartyIdFrom() == null ? 0 : this.getPartyIdFrom().hashCode());
		result = 37 * result + (getRoleTypeIdTo() == null ? 0 : this.getRoleTypeIdTo().hashCode());
		result = 37 * result + (getRoleTypeIdFrom() == null ? 0 : this.getRoleTypeIdFrom().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
