package com.cornerstones.communications.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommunicationEventPurposeId generated by hbm2java
 */
@Embeddable
public class CommunicationEventPurposeId implements java.io.Serializable {

	private String communicationEventPrpTypId;
	private String communicationEventId;

	public CommunicationEventPurposeId() {
	}

	public CommunicationEventPurposeId(String communicationEventPrpTypId, String communicationEventId) {
		this.communicationEventPrpTypId = communicationEventPrpTypId;
		this.communicationEventId = communicationEventId;
	}

	@Column(name = "COMMUNICATION_EVENT_PRP_TYP_ID", nullable = false, length = 20)
	public String getCommunicationEventPrpTypId() {
		return this.communicationEventPrpTypId;
	}

	public void setCommunicationEventPrpTypId(String communicationEventPrpTypId) {
		this.communicationEventPrpTypId = communicationEventPrpTypId;
	}

	@Column(name = "COMMUNICATION_EVENT_ID", nullable = false, length = 20)
	public String getCommunicationEventId() {
		return this.communicationEventId;
	}

	public void setCommunicationEventId(String communicationEventId) {
		this.communicationEventId = communicationEventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommunicationEventPurposeId))
			return false;
		CommunicationEventPurposeId castOther = (CommunicationEventPurposeId) other;

		return ((this.getCommunicationEventPrpTypId() == castOther.getCommunicationEventPrpTypId())
				|| (this.getCommunicationEventPrpTypId() != null && castOther.getCommunicationEventPrpTypId() != null
						&& this.getCommunicationEventPrpTypId().equals(castOther.getCommunicationEventPrpTypId())))
				&& ((this.getCommunicationEventId() == castOther.getCommunicationEventId())
						|| (this.getCommunicationEventId() != null && castOther.getCommunicationEventId() != null
								&& this.getCommunicationEventId().equals(castOther.getCommunicationEventId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCommunicationEventPrpTypId() == null ? 0 : this.getCommunicationEventPrpTypId().hashCode());
		result = 37 * result + (getCommunicationEventId() == null ? 0 : this.getCommunicationEventId().hashCode());
		return result;
	}

}
