package com.cornerstones.communications.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommunicationEventWorkEffId generated by hbm2java
 */
@Embeddable
public class CommunicationEventWorkEffId implements java.io.Serializable {

	private String workEffortId;
	private String communicationEventId;

	public CommunicationEventWorkEffId() {
	}

	public CommunicationEventWorkEffId(String workEffortId, String communicationEventId) {
		this.workEffortId = workEffortId;
		this.communicationEventId = communicationEventId;
	}

	@Column(name = "WORK_EFFORT_ID", nullable = false, length = 20)
	public String getWorkEffortId() {
		return this.workEffortId;
	}

	public void setWorkEffortId(String workEffortId) {
		this.workEffortId = workEffortId;
	}

	@Column(name = "COMMUNICATION_EVENT_ID", nullable = false, length = 20)
	public String getCommunicationEventId() {
		return this.communicationEventId;
	}

	public void setCommunicationEventId(String communicationEventId) {
		this.communicationEventId = communicationEventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommunicationEventWorkEffId))
			return false;
		CommunicationEventWorkEffId castOther = (CommunicationEventWorkEffId) other;

		return ((this.getWorkEffortId() == castOther.getWorkEffortId()) || (this.getWorkEffortId() != null
				&& castOther.getWorkEffortId() != null && this.getWorkEffortId().equals(castOther.getWorkEffortId())))
				&& ((this.getCommunicationEventId() == castOther.getCommunicationEventId())
						|| (this.getCommunicationEventId() != null && castOther.getCommunicationEventId() != null
								&& this.getCommunicationEventId().equals(castOther.getCommunicationEventId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getWorkEffortId() == null ? 0 : this.getWorkEffortId().hashCode());
		result = 37 * result + (getCommunicationEventId() == null ? 0 : this.getCommunicationEventId().hashCode());
		return result;
	}

}
