package com.cornerstones.communications.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommunicationEventRoleId generated by hbm2java
 */
@Embeddable
public class CommunicationEventRoleId implements java.io.Serializable {

	private String communicationEventId;
	private String partyId;
	private String roleTypeId;

	public CommunicationEventRoleId() {
	}

	public CommunicationEventRoleId(String communicationEventId, String partyId, String roleTypeId) {
		this.communicationEventId = communicationEventId;
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
	}

	@Column(name = "COMMUNICATION_EVENT_ID", nullable = false, length = 20)
	public String getCommunicationEventId() {
		return this.communicationEventId;
	}

	public void setCommunicationEventId(String communicationEventId) {
		this.communicationEventId = communicationEventId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "ROLE_TYPE_ID", nullable = false, length = 20)
	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommunicationEventRoleId))
			return false;
		CommunicationEventRoleId castOther = (CommunicationEventRoleId) other;

		return ((this.getCommunicationEventId() == castOther.getCommunicationEventId())
				|| (this.getCommunicationEventId() != null && castOther.getCommunicationEventId() != null
						&& this.getCommunicationEventId().equals(castOther.getCommunicationEventId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId())
						|| (this.getRoleTypeId() != null && castOther.getRoleTypeId() != null
								&& this.getRoleTypeId().equals(castOther.getRoleTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCommunicationEventId() == null ? 0 : this.getCommunicationEventId().hashCode());
		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getRoleTypeId() == null ? 0 : this.getRoleTypeId().hashCode());
		return result;
	}

}
