package com.cornerstones.communications.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommEventContentAssocId generated by hbm2java
 */
@Embeddable
public class CommEventContentAssocId implements java.io.Serializable {

	private String contentId;
	private String communicationEventId;
	private Date fromDate;

	public CommEventContentAssocId() {
	}

	public CommEventContentAssocId(String contentId, String communicationEventId, Date fromDate) {
		this.contentId = contentId;
		this.communicationEventId = communicationEventId;
		this.fromDate = fromDate;
	}

	@Column(name = "CONTENT_ID", nullable = false, length = 20)
	public String getContentId() {
		return this.contentId;
	}

	public void setContentId(String contentId) {
		this.contentId = contentId;
	}

	@Column(name = "COMMUNICATION_EVENT_ID", nullable = false, length = 20)
	public String getCommunicationEventId() {
		return this.communicationEventId;
	}

	public void setCommunicationEventId(String communicationEventId) {
		this.communicationEventId = communicationEventId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommEventContentAssocId))
			return false;
		CommEventContentAssocId castOther = (CommEventContentAssocId) other;

		return ((this.getContentId() == castOther.getContentId()) || (this.getContentId() != null
				&& castOther.getContentId() != null && this.getContentId().equals(castOther.getContentId())))
				&& ((this.getCommunicationEventId() == castOther.getCommunicationEventId())
						|| (this.getCommunicationEventId() != null && castOther.getCommunicationEventId() != null
								&& this.getCommunicationEventId().equals(castOther.getCommunicationEventId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContentId() == null ? 0 : this.getContentId().hashCode());
		result = 37 * result + (getCommunicationEventId() == null ? 0 : this.getCommunicationEventId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
