package com.cornerstones.communications.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommunicationEventProductId generated by hbm2java
 */
@Embeddable
public class CommunicationEventProductId implements java.io.Serializable {

	private String productId;
	private String communicationEventId;

	public CommunicationEventProductId() {
	}

	public CommunicationEventProductId(String productId, String communicationEventId) {
		this.productId = productId;
		this.communicationEventId = communicationEventId;
	}

	@Column(name = "PRODUCT_ID", nullable = false, length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "COMMUNICATION_EVENT_ID", nullable = false, length = 20)
	public String getCommunicationEventId() {
		return this.communicationEventId;
	}

	public void setCommunicationEventId(String communicationEventId) {
		this.communicationEventId = communicationEventId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommunicationEventProductId))
			return false;
		CommunicationEventProductId castOther = (CommunicationEventProductId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null
				&& castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
				&& ((this.getCommunicationEventId() == castOther.getCommunicationEventId())
						|| (this.getCommunicationEventId() != null && castOther.getCommunicationEventId() != null
								&& this.getCommunicationEventId().equals(castOther.getCommunicationEventId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getCommunicationEventId() == null ? 0 : this.getCommunicationEventId().hashCode());
		return result;
	}

}
