package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyContentId generated by hbm2java
 */
@Embeddable
public class PartyContentId implements java.io.Serializable {

	private String partyId;
	private String contentId;
	private String partyContentTypeId;
	private Date fromDate;

	public PartyContentId() {
	}

	public PartyContentId(String partyId, String contentId, String partyContentTypeId, Date fromDate) {
		this.partyId = partyId;
		this.contentId = contentId;
		this.partyContentTypeId = partyContentTypeId;
		this.fromDate = fromDate;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "CONTENT_ID", nullable = false, length = 20)
	public String getContentId() {
		return this.contentId;
	}

	public void setContentId(String contentId) {
		this.contentId = contentId;
	}

	@Column(name = "PARTY_CONTENT_TYPE_ID", nullable = false, length = 20)
	public String getPartyContentTypeId() {
		return this.partyContentTypeId;
	}

	public void setPartyContentTypeId(String partyContentTypeId) {
		this.partyContentTypeId = partyContentTypeId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyContentId))
			return false;
		PartyContentId castOther = (PartyContentId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getContentId() == castOther.getContentId()) || (this.getContentId() != null
						&& castOther.getContentId() != null && this.getContentId().equals(castOther.getContentId())))
				&& ((this.getPartyContentTypeId() == castOther.getPartyContentTypeId())
						|| (this.getPartyContentTypeId() != null && castOther.getPartyContentTypeId() != null
								&& this.getPartyContentTypeId().equals(castOther.getPartyContentTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getContentId() == null ? 0 : this.getContentId().hashCode());
		result = 37 * result + (getPartyContentTypeId() == null ? 0 : this.getPartyContentTypeId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
