package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyGeoPointId generated by hbm2java
 */
@Embeddable
public class PartyGeoPointId implements java.io.Serializable {

	private String partyId;
	private String geoPointId;
	private Date fromDate;

	public PartyGeoPointId() {
	}

	public PartyGeoPointId(String partyId, String geoPointId, Date fromDate) {
		this.partyId = partyId;
		this.geoPointId = geoPointId;
		this.fromDate = fromDate;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "GEO_POINT_ID", nullable = false, length = 20)
	public String getGeoPointId() {
		return this.geoPointId;
	}

	public void setGeoPointId(String geoPointId) {
		this.geoPointId = geoPointId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyGeoPointId))
			return false;
		PartyGeoPointId castOther = (PartyGeoPointId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getGeoPointId() == castOther.getGeoPointId()) || (this.getGeoPointId() != null
						&& castOther.getGeoPointId() != null && this.getGeoPointId().equals(castOther.getGeoPointId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getGeoPointId() == null ? 0 : this.getGeoPointId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
