package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyBenefitId generated by hbm2java
 */
@Embeddable
public class PartyBenefitId implements java.io.Serializable {

	private String roleTypeIdFrom;
	private String roleTypeIdTo;
	private String partyIdFrom;
	private String partyIdTo;
	private String benefitTypeId;
	private Date fromDate;

	public PartyBenefitId() {
	}

	public PartyBenefitId(String roleTypeIdFrom, String roleTypeIdTo, String partyIdFrom, String partyIdTo,
			String benefitTypeId, Date fromDate) {
		this.roleTypeIdFrom = roleTypeIdFrom;
		this.roleTypeIdTo = roleTypeIdTo;
		this.partyIdFrom = partyIdFrom;
		this.partyIdTo = partyIdTo;
		this.benefitTypeId = benefitTypeId;
		this.fromDate = fromDate;
	}

	@Column(name = "ROLE_TYPE_ID_FROM", nullable = false, length = 20)
	public String getRoleTypeIdFrom() {
		return this.roleTypeIdFrom;
	}

	public void setRoleTypeIdFrom(String roleTypeIdFrom) {
		this.roleTypeIdFrom = roleTypeIdFrom;
	}

	@Column(name = "ROLE_TYPE_ID_TO", nullable = false, length = 20)
	public String getRoleTypeIdTo() {
		return this.roleTypeIdTo;
	}

	public void setRoleTypeIdTo(String roleTypeIdTo) {
		this.roleTypeIdTo = roleTypeIdTo;
	}

	@Column(name = "PARTY_ID_FROM", nullable = false, length = 20)
	public String getPartyIdFrom() {
		return this.partyIdFrom;
	}

	public void setPartyIdFrom(String partyIdFrom) {
		this.partyIdFrom = partyIdFrom;
	}

	@Column(name = "PARTY_ID_TO", nullable = false, length = 20)
	public String getPartyIdTo() {
		return this.partyIdTo;
	}

	public void setPartyIdTo(String partyIdTo) {
		this.partyIdTo = partyIdTo;
	}

	@Column(name = "BENEFIT_TYPE_ID", nullable = false, length = 20)
	public String getBenefitTypeId() {
		return this.benefitTypeId;
	}

	public void setBenefitTypeId(String benefitTypeId) {
		this.benefitTypeId = benefitTypeId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyBenefitId))
			return false;
		PartyBenefitId castOther = (PartyBenefitId) other;

		return ((this.getRoleTypeIdFrom() == castOther.getRoleTypeIdFrom())
				|| (this.getRoleTypeIdFrom() != null && castOther.getRoleTypeIdFrom() != null
						&& this.getRoleTypeIdFrom().equals(castOther.getRoleTypeIdFrom())))
				&& ((this.getRoleTypeIdTo() == castOther.getRoleTypeIdTo())
						|| (this.getRoleTypeIdTo() != null && castOther.getRoleTypeIdTo() != null
								&& this.getRoleTypeIdTo().equals(castOther.getRoleTypeIdTo())))
				&& ((this.getPartyIdFrom() == castOther.getPartyIdFrom())
						|| (this.getPartyIdFrom() != null && castOther.getPartyIdFrom() != null
								&& this.getPartyIdFrom().equals(castOther.getPartyIdFrom())))
				&& ((this.getPartyIdTo() == castOther.getPartyIdTo()) || (this.getPartyIdTo() != null
						&& castOther.getPartyIdTo() != null && this.getPartyIdTo().equals(castOther.getPartyIdTo())))
				&& ((this.getBenefitTypeId() == castOther.getBenefitTypeId())
						|| (this.getBenefitTypeId() != null && castOther.getBenefitTypeId() != null
								&& this.getBenefitTypeId().equals(castOther.getBenefitTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleTypeIdFrom() == null ? 0 : this.getRoleTypeIdFrom().hashCode());
		result = 37 * result + (getRoleTypeIdTo() == null ? 0 : this.getRoleTypeIdTo().hashCode());
		result = 37 * result + (getPartyIdFrom() == null ? 0 : this.getPartyIdFrom().hashCode());
		result = 37 * result + (getPartyIdTo() == null ? 0 : this.getPartyIdTo().hashCode());
		result = 37 * result + (getBenefitTypeId() == null ? 0 : this.getBenefitTypeId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
