package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyProfileDefault generated by hbm2java
 */
@Entity
@Table(name = "PARTY_PROFILE_DEFAULT", catalog = "ofbiz")
public class PartyProfileDefault implements java.io.Serializable {

	private PartyProfileDefaultId id;
	private String defaultShipAddr;
	private String defaultBillAddr;
	private String defaultPayMeth;
	private String defaultShipMeth;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public PartyProfileDefault() {
	}

	public PartyProfileDefault(PartyProfileDefaultId id) {
		this.id = id;
	}

	public PartyProfileDefault(PartyProfileDefaultId id, String defaultShipAddr, String defaultBillAddr,
			String defaultPayMeth, String defaultShipMeth, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.defaultShipAddr = defaultShipAddr;
		this.defaultBillAddr = defaultBillAddr;
		this.defaultPayMeth = defaultPayMeth;
		this.defaultShipMeth = defaultShipMeth;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "partyId", column = @Column(name = "PARTY_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "productStoreId", column = @Column(name = "PRODUCT_STORE_ID", nullable = false, length = 20) ) })
	public PartyProfileDefaultId getId() {
		return this.id;
	}

	public void setId(PartyProfileDefaultId id) {
		this.id = id;
	}

	@Column(name = "DEFAULT_SHIP_ADDR", length = 20)
	public String getDefaultShipAddr() {
		return this.defaultShipAddr;
	}

	public void setDefaultShipAddr(String defaultShipAddr) {
		this.defaultShipAddr = defaultShipAddr;
	}

	@Column(name = "DEFAULT_BILL_ADDR", length = 20)
	public String getDefaultBillAddr() {
		return this.defaultBillAddr;
	}

	public void setDefaultBillAddr(String defaultBillAddr) {
		this.defaultBillAddr = defaultBillAddr;
	}

	@Column(name = "DEFAULT_PAY_METH", length = 20)
	public String getDefaultPayMeth() {
		return this.defaultPayMeth;
	}

	public void setDefaultPayMeth(String defaultPayMeth) {
		this.defaultPayMeth = defaultPayMeth;
	}

	@Column(name = "DEFAULT_SHIP_METH", length = 20)
	public String getDefaultShipMeth() {
		return this.defaultShipMeth;
	}

	public void setDefaultShipMeth(String defaultShipMeth) {
		this.defaultShipMeth = defaultShipMeth;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
