package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyStatusId generated by hbm2java
 */
@Embeddable
public class PartyStatusId implements java.io.Serializable {

	private String statusId;
	private String partyId;
	private Date statusDate;

	public PartyStatusId() {
	}

	public PartyStatusId(String statusId, String partyId, Date statusDate) {
		this.statusId = statusId;
		this.partyId = partyId;
		this.statusDate = statusDate;
	}

	@Column(name = "STATUS_ID", nullable = false, length = 20)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "STATUS_DATE", nullable = false, length = 19)
	public Date getStatusDate() {
		return this.statusDate;
	}

	public void setStatusDate(Date statusDate) {
		this.statusDate = statusDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyStatusId))
			return false;
		PartyStatusId castOther = (PartyStatusId) other;

		return ((this.getStatusId() == castOther.getStatusId()) || (this.getStatusId() != null
				&& castOther.getStatusId() != null && this.getStatusId().equals(castOther.getStatusId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getStatusDate() == castOther.getStatusDate())
						|| (this.getStatusDate() != null && castOther.getStatusDate() != null
								&& this.getStatusDate().equals(castOther.getStatusDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStatusId() == null ? 0 : this.getStatusId().hashCode());
		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getStatusDate() == null ? 0 : this.getStatusDate().hashCode());
		return result;
	}

}
