package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyGroup generated by hbm2java
 */
@Entity
@Table(name = "party_group", catalog = "ofbiz")
public class PartyGroup implements java.io.Serializable {

	private String partyId;
	private String groupName;
	private String groupNameLocal;
	private String officeSiteName;
	private BigDecimal annualRevenue;
	private BigDecimal numEmployees;
	private String tickerSymbol;
	private String comments;
	private String logoImageUrl;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;
	private String ticketSymbol;

	public PartyGroup() {
	}

	public PartyGroup(String partyId) {
		this.partyId = partyId;
	}

	public PartyGroup(String partyId, String groupName, String groupNameLocal, String officeSiteName,
			BigDecimal annualRevenue, BigDecimal numEmployees, String tickerSymbol, String comments,
			String logoImageUrl, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp,
			String ticketSymbol) {
		this.partyId = partyId;
		this.groupName = groupName;
		this.groupNameLocal = groupNameLocal;
		this.officeSiteName = officeSiteName;
		this.annualRevenue = annualRevenue;
		this.numEmployees = numEmployees;
		this.tickerSymbol = tickerSymbol;
		this.comments = comments;
		this.logoImageUrl = logoImageUrl;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
		this.ticketSymbol = ticketSymbol;
	}

	@Id

	@Column(name = "PARTY_ID", unique = true, nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "GROUP_NAME", length = 100)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "GROUP_NAME_LOCAL", length = 100)
	public String getGroupNameLocal() {
		return this.groupNameLocal;
	}

	public void setGroupNameLocal(String groupNameLocal) {
		this.groupNameLocal = groupNameLocal;
	}

	@Column(name = "OFFICE_SITE_NAME", length = 100)
	public String getOfficeSiteName() {
		return this.officeSiteName;
	}

	public void setOfficeSiteName(String officeSiteName) {
		this.officeSiteName = officeSiteName;
	}

	@Column(name = "ANNUAL_REVENUE", precision = 18)
	public BigDecimal getAnnualRevenue() {
		return this.annualRevenue;
	}

	public void setAnnualRevenue(BigDecimal annualRevenue) {
		this.annualRevenue = annualRevenue;
	}

	@Column(name = "NUM_EMPLOYEES", precision = 20, scale = 0)
	public BigDecimal getNumEmployees() {
		return this.numEmployees;
	}

	public void setNumEmployees(BigDecimal numEmployees) {
		this.numEmployees = numEmployees;
	}

	@Column(name = "TICKER_SYMBOL", length = 10)
	public String getTickerSymbol() {
		return this.tickerSymbol;
	}

	public void setTickerSymbol(String tickerSymbol) {
		this.tickerSymbol = tickerSymbol;
	}

	@Column(name = "COMMENTS")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "LOGO_IMAGE_URL")
	public String getLogoImageUrl() {
		return this.logoImageUrl;
	}

	public void setLogoImageUrl(String logoImageUrl) {
		this.logoImageUrl = logoImageUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

	@Column(name = "ticket_symbol")
	public String getTicketSymbol() {
		return this.ticketSymbol;
	}

	public void setTicketSymbol(String ticketSymbol) {
		this.ticketSymbol = ticketSymbol;
	}

}
