package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyInvitation generated by hbm2java
 */
@Entity
@Table(name = "PARTY_INVITATION", catalog = "ofbiz")
public class PartyInvitation implements java.io.Serializable {

	private String partyInvitationId;
	private String partyIdFrom;
	private String partyId;
	private String toName;
	private String emailAddress;
	private String statusId;
	private Date lastInviteDate;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public PartyInvitation() {
	}

	public PartyInvitation(String partyInvitationId) {
		this.partyInvitationId = partyInvitationId;
	}

	public PartyInvitation(String partyInvitationId, String partyIdFrom, String partyId, String toName,
			String emailAddress, String statusId, Date lastInviteDate, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.partyInvitationId = partyInvitationId;
		this.partyIdFrom = partyIdFrom;
		this.partyId = partyId;
		this.toName = toName;
		this.emailAddress = emailAddress;
		this.statusId = statusId;
		this.lastInviteDate = lastInviteDate;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@Id

	@Column(name = "PARTY_INVITATION_ID", unique = true, nullable = false, length = 20)
	public String getPartyInvitationId() {
		return this.partyInvitationId;
	}

	public void setPartyInvitationId(String partyInvitationId) {
		this.partyInvitationId = partyInvitationId;
	}

	@Column(name = "PARTY_ID_FROM", length = 20)
	public String getPartyIdFrom() {
		return this.partyIdFrom;
	}

	public void setPartyIdFrom(String partyIdFrom) {
		this.partyIdFrom = partyIdFrom;
	}

	@Column(name = "PARTY_ID", length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "TO_NAME", length = 100)
	public String getToName() {
		return this.toName;
	}

	public void setToName(String toName) {
		this.toName = toName;
	}

	@Column(name = "EMAIL_ADDRESS")
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "STATUS_ID", length = 20)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_INVITE_DATE", length = 19)
	public Date getLastInviteDate() {
		return this.lastInviteDate;
	}

	public void setLastInviteDate(Date lastInviteDate) {
		this.lastInviteDate = lastInviteDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
