package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyNeedId generated by hbm2java
 */
@Embeddable
public class PartyNeedId implements java.io.Serializable {

	private String partyNeedId;
	private String partyId;
	private String roleTypeId;

	public PartyNeedId() {
	}

	public PartyNeedId(String partyNeedId, String partyId, String roleTypeId) {
		this.partyNeedId = partyNeedId;
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
	}

	@Column(name = "PARTY_NEED_ID", nullable = false, length = 20)
	public String getPartyNeedId() {
		return this.partyNeedId;
	}

	public void setPartyNeedId(String partyNeedId) {
		this.partyNeedId = partyNeedId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "ROLE_TYPE_ID", nullable = false, length = 20)
	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyNeedId))
			return false;
		PartyNeedId castOther = (PartyNeedId) other;

		return ((this.getPartyNeedId() == castOther.getPartyNeedId()) || (this.getPartyNeedId() != null
				&& castOther.getPartyNeedId() != null && this.getPartyNeedId().equals(castOther.getPartyNeedId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId())
						|| (this.getRoleTypeId() != null && castOther.getRoleTypeId() != null
								&& this.getRoleTypeId().equals(castOther.getRoleTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyNeedId() == null ? 0 : this.getPartyNeedId().hashCode());
		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getRoleTypeId() == null ? 0 : this.getRoleTypeId().hashCode());
		return result;
	}

}
