package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyCarrierAccountId generated by hbm2java
 */
@Embeddable
public class PartyCarrierAccountId implements java.io.Serializable {

	private String partyId;
	private String carrierPartyId;
	private Date fromDate;

	public PartyCarrierAccountId() {
	}

	public PartyCarrierAccountId(String partyId, String carrierPartyId, Date fromDate) {
		this.partyId = partyId;
		this.carrierPartyId = carrierPartyId;
		this.fromDate = fromDate;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "CARRIER_PARTY_ID", nullable = false, length = 20)
	public String getCarrierPartyId() {
		return this.carrierPartyId;
	}

	public void setCarrierPartyId(String carrierPartyId) {
		this.carrierPartyId = carrierPartyId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyCarrierAccountId))
			return false;
		PartyCarrierAccountId castOther = (PartyCarrierAccountId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getCarrierPartyId() == castOther.getCarrierPartyId())
						|| (this.getCarrierPartyId() != null && castOther.getCarrierPartyId() != null
								&& this.getCarrierPartyId().equals(castOther.getCarrierPartyId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getCarrierPartyId() == null ? 0 : this.getCarrierPartyId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
