package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyGlAccountId generated by hbm2java
 */
@Embeddable
public class PartyGlAccountId implements java.io.Serializable {

	private String organizationPartyId;
	private String partyId;
	private String roleTypeId;
	private String glAccountTypeId;

	public PartyGlAccountId() {
	}

	public PartyGlAccountId(String organizationPartyId, String partyId, String roleTypeId, String glAccountTypeId) {
		this.organizationPartyId = organizationPartyId;
		this.partyId = partyId;
		this.roleTypeId = roleTypeId;
		this.glAccountTypeId = glAccountTypeId;
	}

	@Column(name = "ORGANIZATION_PARTY_ID", nullable = false, length = 20)
	public String getOrganizationPartyId() {
		return this.organizationPartyId;
	}

	public void setOrganizationPartyId(String organizationPartyId) {
		this.organizationPartyId = organizationPartyId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "ROLE_TYPE_ID", nullable = false, length = 20)
	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	@Column(name = "GL_ACCOUNT_TYPE_ID", nullable = false, length = 20)
	public String getGlAccountTypeId() {
		return this.glAccountTypeId;
	}

	public void setGlAccountTypeId(String glAccountTypeId) {
		this.glAccountTypeId = glAccountTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyGlAccountId))
			return false;
		PartyGlAccountId castOther = (PartyGlAccountId) other;

		return ((this.getOrganizationPartyId() == castOther.getOrganizationPartyId())
				|| (this.getOrganizationPartyId() != null && castOther.getOrganizationPartyId() != null
						&& this.getOrganizationPartyId().equals(castOther.getOrganizationPartyId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId()) || (this.getRoleTypeId() != null
						&& castOther.getRoleTypeId() != null && this.getRoleTypeId().equals(castOther.getRoleTypeId())))
				&& ((this.getGlAccountTypeId() == castOther.getGlAccountTypeId())
						|| (this.getGlAccountTypeId() != null && castOther.getGlAccountTypeId() != null
								&& this.getGlAccountTypeId().equals(castOther.getGlAccountTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrganizationPartyId() == null ? 0 : this.getOrganizationPartyId().hashCode());
		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getRoleTypeId() == null ? 0 : this.getRoleTypeId().hashCode());
		result = 37 * result + (getGlAccountTypeId() == null ? 0 : this.getGlAccountTypeId().hashCode());
		return result;
	}

}
