package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartySkillId generated by hbm2java
 */
@Embeddable
public class PartySkillId implements java.io.Serializable {

	private String partyId;
	private String skillTypeId;

	public PartySkillId() {
	}

	public PartySkillId(String partyId, String skillTypeId) {
		this.partyId = partyId;
		this.skillTypeId = skillTypeId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "SKILL_TYPE_ID", nullable = false, length = 20)
	public String getSkillTypeId() {
		return this.skillTypeId;
	}

	public void setSkillTypeId(String skillTypeId) {
		this.skillTypeId = skillTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartySkillId))
			return false;
		PartySkillId castOther = (PartySkillId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getSkillTypeId() == castOther.getSkillTypeId())
						|| (this.getSkillTypeId() != null && castOther.getSkillTypeId() != null
								&& this.getSkillTypeId().equals(castOther.getSkillTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getSkillTypeId() == null ? 0 : this.getSkillTypeId().hashCode());
		return result;
	}

}
