package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyInvitationRoleAssocId generated by hbm2java
 */
@Embeddable
public class PartyInvitationRoleAssocId implements java.io.Serializable {

	private String partyInvitationId;
	private String roleTypeId;

	public PartyInvitationRoleAssocId() {
	}

	public PartyInvitationRoleAssocId(String partyInvitationId, String roleTypeId) {
		this.partyInvitationId = partyInvitationId;
		this.roleTypeId = roleTypeId;
	}

	@Column(name = "PARTY_INVITATION_ID", nullable = false, length = 20)
	public String getPartyInvitationId() {
		return this.partyInvitationId;
	}

	public void setPartyInvitationId(String partyInvitationId) {
		this.partyInvitationId = partyInvitationId;
	}

	@Column(name = "ROLE_TYPE_ID", nullable = false, length = 20)
	public String getRoleTypeId() {
		return this.roleTypeId;
	}

	public void setRoleTypeId(String roleTypeId) {
		this.roleTypeId = roleTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyInvitationRoleAssocId))
			return false;
		PartyInvitationRoleAssocId castOther = (PartyInvitationRoleAssocId) other;

		return ((this.getPartyInvitationId() == castOther.getPartyInvitationId())
				|| (this.getPartyInvitationId() != null && castOther.getPartyInvitationId() != null
						&& this.getPartyInvitationId().equals(castOther.getPartyInvitationId())))
				&& ((this.getRoleTypeId() == castOther.getRoleTypeId())
						|| (this.getRoleTypeId() != null && castOther.getRoleTypeId() != null
								&& this.getRoleTypeId().equals(castOther.getRoleTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyInvitationId() == null ? 0 : this.getPartyInvitationId().hashCode());
		result = 37 * result + (getRoleTypeId() == null ? 0 : this.getRoleTypeId().hashCode());
		return result;
	}

}
