package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyNeed generated by hbm2java
 */
@Entity
@Table(name = "PARTY_NEED", catalog = "ofbiz")
public class PartyNeed implements java.io.Serializable {

	private PartyNeedId id;
	private String partyTypeId;
	private String needTypeId;
	private String communicationEventId;
	private String productId;
	private String productCategoryId;
	private String visitId;
	private Date datetimeRecorded;
	private String description;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public PartyNeed() {
	}

	public PartyNeed(PartyNeedId id) {
		this.id = id;
	}

	public PartyNeed(PartyNeedId id, String partyTypeId, String needTypeId, String communicationEventId,
			String productId, String productCategoryId, String visitId, Date datetimeRecorded, String description,
			Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.partyTypeId = partyTypeId;
		this.needTypeId = needTypeId;
		this.communicationEventId = communicationEventId;
		this.productId = productId;
		this.productCategoryId = productCategoryId;
		this.visitId = visitId;
		this.datetimeRecorded = datetimeRecorded;
		this.description = description;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "partyNeedId", column = @Column(name = "PARTY_NEED_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "partyId", column = @Column(name = "PARTY_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "roleTypeId", column = @Column(name = "ROLE_TYPE_ID", nullable = false, length = 20) ) })
	public PartyNeedId getId() {
		return this.id;
	}

	public void setId(PartyNeedId id) {
		this.id = id;
	}

	@Column(name = "PARTY_TYPE_ID", length = 20)
	public String getPartyTypeId() {
		return this.partyTypeId;
	}

	public void setPartyTypeId(String partyTypeId) {
		this.partyTypeId = partyTypeId;
	}

	@Column(name = "NEED_TYPE_ID", length = 20)
	public String getNeedTypeId() {
		return this.needTypeId;
	}

	public void setNeedTypeId(String needTypeId) {
		this.needTypeId = needTypeId;
	}

	@Column(name = "COMMUNICATION_EVENT_ID", length = 20)
	public String getCommunicationEventId() {
		return this.communicationEventId;
	}

	public void setCommunicationEventId(String communicationEventId) {
		this.communicationEventId = communicationEventId;
	}

	@Column(name = "PRODUCT_ID", length = 20)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "PRODUCT_CATEGORY_ID", length = 20)
	public String getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(String productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

	@Column(name = "VISIT_ID", length = 20)
	public String getVisitId() {
		return this.visitId;
	}

	public void setVisitId(String visitId) {
		this.visitId = visitId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATETIME_RECORDED", length = 19)
	public Date getDatetimeRecorded() {
		return this.datetimeRecorded;
	}

	public void setDatetimeRecorded(Date datetimeRecorded) {
		this.datetimeRecorded = datetimeRecorded;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
