package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyClassificationId generated by hbm2java
 */
@Embeddable
public class PartyClassificationId implements java.io.Serializable {

	private String partyId;
	private String partyClassificationGroupId;
	private Date fromDate;

	public PartyClassificationId() {
	}

	public PartyClassificationId(String partyId, String partyClassificationGroupId, Date fromDate) {
		this.partyId = partyId;
		this.partyClassificationGroupId = partyClassificationGroupId;
		this.fromDate = fromDate;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "PARTY_CLASSIFICATION_GROUP_ID", nullable = false, length = 20)
	public String getPartyClassificationGroupId() {
		return this.partyClassificationGroupId;
	}

	public void setPartyClassificationGroupId(String partyClassificationGroupId) {
		this.partyClassificationGroupId = partyClassificationGroupId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyClassificationId))
			return false;
		PartyClassificationId castOther = (PartyClassificationId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getPartyClassificationGroupId() == castOther.getPartyClassificationGroupId())
						|| (this.getPartyClassificationGroupId() != null
								&& castOther.getPartyClassificationGroupId() != null
								&& this.getPartyClassificationGroupId()
										.equals(castOther.getPartyClassificationGroupId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result
				+ (getPartyClassificationGroupId() == null ? 0 : this.getPartyClassificationGroupId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
