package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyBenefit generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PARTY_BENEFIT", catalog = "ofbiz")
public class PartyBenefit implements java.io.Serializable {

	private PartyBenefitId id;
	private Date thruDate;
	private String periodTypeId;
	private BigDecimal cost;
	private Double actualEmployerPaidPercent;
	private BigDecimal availableTime;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public PartyBenefit() {
	}

	public PartyBenefit(PartyBenefitId id) {
		this.id = id;
	}

	public PartyBenefit(PartyBenefitId id, Date thruDate, String periodTypeId, BigDecimal cost,
			Double actualEmployerPaidPercent, BigDecimal availableTime, Date lastUpdatedStamp, Date lastUpdatedTxStamp,
			Date createdStamp, Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.periodTypeId = periodTypeId;
		this.cost = cost;
		this.actualEmployerPaidPercent = actualEmployerPaidPercent;
		this.availableTime = availableTime;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleTypeIdFrom", column = @Column(name = "ROLE_TYPE_ID_FROM", nullable = false, length = 20) ),
			@AttributeOverride(name = "roleTypeIdTo", column = @Column(name = "ROLE_TYPE_ID_TO", nullable = false, length = 20) ),
			@AttributeOverride(name = "partyIdFrom", column = @Column(name = "PARTY_ID_FROM", nullable = false, length = 20) ),
			@AttributeOverride(name = "partyIdTo", column = @Column(name = "PARTY_ID_TO", nullable = false, length = 20) ),
			@AttributeOverride(name = "benefitTypeId", column = @Column(name = "BENEFIT_TYPE_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 19) ) })
	public PartyBenefitId getId() {
		return this.id;
	}

	public void setId(PartyBenefitId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THRU_DATE", length = 19)
	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	@Column(name = "PERIOD_TYPE_ID", length = 20)
	public String getPeriodTypeId() {
		return this.periodTypeId;
	}

	public void setPeriodTypeId(String periodTypeId) {
		this.periodTypeId = periodTypeId;
	}

	@Column(name = "COST", precision = 18)
	public BigDecimal getCost() {
		return this.cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Column(name = "ACTUAL_EMPLOYER_PAID_PERCENT", precision = 22, scale = 0)
	public Double getActualEmployerPaidPercent() {
		return this.actualEmployerPaidPercent;
	}

	public void setActualEmployerPaidPercent(Double actualEmployerPaidPercent) {
		this.actualEmployerPaidPercent = actualEmployerPaidPercent;
	}

	@Column(name = "AVAILABLE_TIME", precision = 20, scale = 0)
	public BigDecimal getAvailableTime() {
		return this.availableTime;
	}

	public void setAvailableTime(BigDecimal availableTime) {
		this.availableTime = availableTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
