package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyInvitationGroupAssocId generated by hbm2java
 */
@Embeddable
public class PartyInvitationGroupAssocId implements java.io.Serializable {

	private String partyInvitationId;
	private String partyIdTo;

	public PartyInvitationGroupAssocId() {
	}

	public PartyInvitationGroupAssocId(String partyInvitationId, String partyIdTo) {
		this.partyInvitationId = partyInvitationId;
		this.partyIdTo = partyIdTo;
	}

	@Column(name = "PARTY_INVITATION_ID", nullable = false, length = 20)
	public String getPartyInvitationId() {
		return this.partyInvitationId;
	}

	public void setPartyInvitationId(String partyInvitationId) {
		this.partyInvitationId = partyInvitationId;
	}

	@Column(name = "PARTY_ID_TO", nullable = false, length = 20)
	public String getPartyIdTo() {
		return this.partyIdTo;
	}

	public void setPartyIdTo(String partyIdTo) {
		this.partyIdTo = partyIdTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyInvitationGroupAssocId))
			return false;
		PartyInvitationGroupAssocId castOther = (PartyInvitationGroupAssocId) other;

		return ((this.getPartyInvitationId() == castOther.getPartyInvitationId())
				|| (this.getPartyInvitationId() != null && castOther.getPartyInvitationId() != null
						&& this.getPartyInvitationId().equals(castOther.getPartyInvitationId())))
				&& ((this.getPartyIdTo() == castOther.getPartyIdTo()) || (this.getPartyIdTo() != null
						&& castOther.getPartyIdTo() != null && this.getPartyIdTo().equals(castOther.getPartyIdTo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyInvitationId() == null ? 0 : this.getPartyInvitationId().hashCode());
		result = 37 * result + (getPartyIdTo() == null ? 0 : this.getPartyIdTo().hashCode());
		return result;
	}

}
