package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyTaxAuthInfoId generated by hbm2java
 */
@Embeddable
public class PartyTaxAuthInfoId implements java.io.Serializable {

	private String partyId;
	private String taxAuthGeoId;
	private String taxAuthPartyId;
	private Date fromDate;

	public PartyTaxAuthInfoId() {
	}

	public PartyTaxAuthInfoId(String partyId, String taxAuthGeoId, String taxAuthPartyId, Date fromDate) {
		this.partyId = partyId;
		this.taxAuthGeoId = taxAuthGeoId;
		this.taxAuthPartyId = taxAuthPartyId;
		this.fromDate = fromDate;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "TAX_AUTH_GEO_ID", nullable = false, length = 20)
	public String getTaxAuthGeoId() {
		return this.taxAuthGeoId;
	}

	public void setTaxAuthGeoId(String taxAuthGeoId) {
		this.taxAuthGeoId = taxAuthGeoId;
	}

	@Column(name = "TAX_AUTH_PARTY_ID", nullable = false, length = 20)
	public String getTaxAuthPartyId() {
		return this.taxAuthPartyId;
	}

	public void setTaxAuthPartyId(String taxAuthPartyId) {
		this.taxAuthPartyId = taxAuthPartyId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyTaxAuthInfoId))
			return false;
		PartyTaxAuthInfoId castOther = (PartyTaxAuthInfoId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getTaxAuthGeoId() == castOther.getTaxAuthGeoId())
						|| (this.getTaxAuthGeoId() != null && castOther.getTaxAuthGeoId() != null
								&& this.getTaxAuthGeoId().equals(castOther.getTaxAuthGeoId())))
				&& ((this.getTaxAuthPartyId() == castOther.getTaxAuthPartyId())
						|| (this.getTaxAuthPartyId() != null && castOther.getTaxAuthPartyId() != null
								&& this.getTaxAuthPartyId().equals(castOther.getTaxAuthPartyId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getTaxAuthGeoId() == null ? 0 : this.getTaxAuthGeoId().hashCode());
		result = 37 * result + (getTaxAuthPartyId() == null ? 0 : this.getTaxAuthPartyId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
