package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyRelationship generated by hbm2java
 */
@Entity
@Table(name = "PARTY_RELATIONSHIP", catalog = "ofbiz")
public class PartyRelationship implements java.io.Serializable {

	private PartyRelationshipId id;
	private Date thruDate;
	private String statusId;
	private String relationshipName;
	private String securityGroupId;
	private String priorityTypeId;
	private String partyRelationshipTypeId;
	private String permissionsEnumId;
	private String positionTitle;
	private String comments;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public PartyRelationship() {
	}

	public PartyRelationship(PartyRelationshipId id) {
		this.id = id;
	}

	public PartyRelationship(PartyRelationshipId id, Date thruDate, String statusId, String relationshipName,
			String securityGroupId, String priorityTypeId, String partyRelationshipTypeId, String permissionsEnumId,
			String positionTitle, String comments, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.thruDate = thruDate;
		this.statusId = statusId;
		this.relationshipName = relationshipName;
		this.securityGroupId = securityGroupId;
		this.priorityTypeId = priorityTypeId;
		this.partyRelationshipTypeId = partyRelationshipTypeId;
		this.permissionsEnumId = permissionsEnumId;
		this.positionTitle = positionTitle;
		this.comments = comments;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "partyIdFrom", column = @Column(name = "PARTY_ID_FROM", nullable = false, length = 20) ),
			@AttributeOverride(name = "partyIdTo", column = @Column(name = "PARTY_ID_TO", nullable = false, length = 20) ),
			@AttributeOverride(name = "roleTypeIdFrom", column = @Column(name = "ROLE_TYPE_ID_FROM", nullable = false, length = 20) ),
			@AttributeOverride(name = "roleTypeIdTo", column = @Column(name = "ROLE_TYPE_ID_TO", nullable = false, length = 20) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 19) ) })
	public PartyRelationshipId getId() {
		return this.id;
	}

	public void setId(PartyRelationshipId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "THRU_DATE", length = 19)
	public Date getThruDate() {
		return this.thruDate;
	}

	public void setThruDate(Date thruDate) {
		this.thruDate = thruDate;
	}

	@Column(name = "STATUS_ID", length = 20)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "RELATIONSHIP_NAME", length = 100)
	public String getRelationshipName() {
		return this.relationshipName;
	}

	public void setRelationshipName(String relationshipName) {
		this.relationshipName = relationshipName;
	}

	@Column(name = "SECURITY_GROUP_ID", length = 20)
	public String getSecurityGroupId() {
		return this.securityGroupId;
	}

	public void setSecurityGroupId(String securityGroupId) {
		this.securityGroupId = securityGroupId;
	}

	@Column(name = "PRIORITY_TYPE_ID", length = 20)
	public String getPriorityTypeId() {
		return this.priorityTypeId;
	}

	public void setPriorityTypeId(String priorityTypeId) {
		this.priorityTypeId = priorityTypeId;
	}

	@Column(name = "PARTY_RELATIONSHIP_TYPE_ID", length = 20)
	public String getPartyRelationshipTypeId() {
		return this.partyRelationshipTypeId;
	}

	public void setPartyRelationshipTypeId(String partyRelationshipTypeId) {
		this.partyRelationshipTypeId = partyRelationshipTypeId;
	}

	@Column(name = "PERMISSIONS_ENUM_ID", length = 20)
	public String getPermissionsEnumId() {
		return this.permissionsEnumId;
	}

	public void setPermissionsEnumId(String permissionsEnumId) {
		this.permissionsEnumId = permissionsEnumId;
	}

	@Column(name = "POSITION_TITLE", length = 100)
	public String getPositionTitle() {
		return this.positionTitle;
	}

	public void setPositionTitle(String positionTitle) {
		this.positionTitle = positionTitle;
	}

	@Column(name = "COMMENTS")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
