package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyTypeAttrId generated by hbm2java
 */
@Embeddable
public class PartyTypeAttrId implements java.io.Serializable {

	private String partyTypeId;
	private String attrName;

	public PartyTypeAttrId() {
	}

	public PartyTypeAttrId(String partyTypeId, String attrName) {
		this.partyTypeId = partyTypeId;
		this.attrName = attrName;
	}

	@Column(name = "PARTY_TYPE_ID", nullable = false, length = 20)
	public String getPartyTypeId() {
		return this.partyTypeId;
	}

	public void setPartyTypeId(String partyTypeId) {
		this.partyTypeId = partyTypeId;
	}

	@Column(name = "ATTR_NAME", nullable = false, length = 60)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyTypeAttrId))
			return false;
		PartyTypeAttrId castOther = (PartyTypeAttrId) other;

		return ((this.getPartyTypeId() == castOther.getPartyTypeId()) || (this.getPartyTypeId() != null
				&& castOther.getPartyTypeId() != null && this.getPartyTypeId().equals(castOther.getPartyTypeId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this.getAttrName() != null
						&& castOther.getAttrName() != null && this.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyTypeId() == null ? 0 : this.getPartyTypeId().hashCode());
		result = 37 * result + (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}
