package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyContactMechPurposeId generated by hbm2java
 */
@Embeddable
public class PartyContactMechPurposeId implements java.io.Serializable {

	private String partyId;
	private String contactMechId;
	private String contactMechPurposeTypeId;
	private Date fromDate;

	public PartyContactMechPurposeId() {
	}

	public PartyContactMechPurposeId(String partyId, String contactMechId, String contactMechPurposeTypeId,
			Date fromDate) {
		this.partyId = partyId;
		this.contactMechId = contactMechId;
		this.contactMechPurposeTypeId = contactMechPurposeTypeId;
		this.fromDate = fromDate;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "CONTACT_MECH_ID", nullable = false, length = 20)
	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	@Column(name = "CONTACT_MECH_PURPOSE_TYPE_ID", nullable = false, length = 20)
	public String getContactMechPurposeTypeId() {
		return this.contactMechPurposeTypeId;
	}

	public void setContactMechPurposeTypeId(String contactMechPurposeTypeId) {
		this.contactMechPurposeTypeId = contactMechPurposeTypeId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PartyContactMechPurposeId))
			return false;
		PartyContactMechPurposeId castOther = (PartyContactMechPurposeId) other;

		return ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
				&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getContactMechId() == castOther.getContactMechId())
						|| (this.getContactMechId() != null && castOther.getContactMechId() != null
								&& this.getContactMechId().equals(castOther.getContactMechId())))
				&& ((this.getContactMechPurposeTypeId() == castOther.getContactMechPurposeTypeId())
						|| (this.getContactMechPurposeTypeId() != null
								&& castOther.getContactMechPurposeTypeId() != null
								&& this.getContactMechPurposeTypeId().equals(castOther.getContactMechPurposeTypeId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getContactMechId() == null ? 0 : this.getContactMechId().hashCode());
		result = 37 * result
				+ (getContactMechPurposeTypeId() == null ? 0 : this.getContactMechPurposeTypeId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
