package com.cornerstones.models.party;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyClassificationGroup generated by hbm2java
 */
@Entity
@Table(name = "PARTY_CLASSIFICATION_GROUP", catalog = "ofbiz")
public class PartyClassificationGroup implements java.io.Serializable {

	private String partyClassificationGroupId;
	private String partyClassificationTypeId;
	private String parentGroupId;
	private String description;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public PartyClassificationGroup() {
	}

	public PartyClassificationGroup(String partyClassificationGroupId) {
		this.partyClassificationGroupId = partyClassificationGroupId;
	}

	public PartyClassificationGroup(String partyClassificationGroupId, String partyClassificationTypeId,
			String parentGroupId, String description, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.partyClassificationGroupId = partyClassificationGroupId;
		this.partyClassificationTypeId = partyClassificationTypeId;
		this.parentGroupId = parentGroupId;
		this.description = description;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@Id

	@Column(name = "PARTY_CLASSIFICATION_GROUP_ID", unique = true, nullable = false, length = 20)
	public String getPartyClassificationGroupId() {
		return this.partyClassificationGroupId;
	}

	public void setPartyClassificationGroupId(String partyClassificationGroupId) {
		this.partyClassificationGroupId = partyClassificationGroupId;
	}

	@Column(name = "PARTY_CLASSIFICATION_TYPE_ID", length = 20)
	public String getPartyClassificationTypeId() {
		return this.partyClassificationTypeId;
	}

	public void setPartyClassificationTypeId(String partyClassificationTypeId) {
		this.partyClassificationTypeId = partyClassificationTypeId;
	}

	@Column(name = "PARENT_GROUP_ID", length = 20)
	public String getParentGroupId() {
		return this.parentGroupId;
	}

	public void setParentGroupId(String parentGroupId) {
		this.parentGroupId = parentGroupId;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
