package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactMechTypeAttrId generated by hbm2java
 */
@Embeddable
public class ContactMechTypeAttrId implements java.io.Serializable {

	private String contactMechTypeId;
	private String attrName;

	public ContactMechTypeAttrId() {
	}

	public ContactMechTypeAttrId(String contactMechTypeId, String attrName) {
		this.contactMechTypeId = contactMechTypeId;
		this.attrName = attrName;
	}

	@Column(name = "CONTACT_MECH_TYPE_ID", nullable = false, length = 20)
	public String getContactMechTypeId() {
		return this.contactMechTypeId;
	}

	public void setContactMechTypeId(String contactMechTypeId) {
		this.contactMechTypeId = contactMechTypeId;
	}

	@Column(name = "ATTR_NAME", nullable = false, length = 60)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactMechTypeAttrId))
			return false;
		ContactMechTypeAttrId castOther = (ContactMechTypeAttrId) other;

		return ((this.getContactMechTypeId() == castOther.getContactMechTypeId())
				|| (this.getContactMechTypeId() != null && castOther.getContactMechTypeId() != null
						&& this.getContactMechTypeId().equals(castOther.getContactMechTypeId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this.getAttrName() != null
						&& castOther.getAttrName() != null && this.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContactMechTypeId() == null ? 0 : this.getContactMechTypeId().hashCode());
		result = 37 * result + (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}
