package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactMech generated by hbm2java
 */
@Entity
@Table(name = "contact_mech", catalog = "ofbiz")
public class ContactMech implements java.io.Serializable {

	private String contactMechId;
	private String contactMechTypeId;
	private String infoString;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;
	private String infoSession;

	public ContactMech() {
	}

	public ContactMech(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	public ContactMech(String contactMechId, String contactMechTypeId, String infoString, Date lastUpdatedStamp,
			Date lastUpdatedTxStamp, Date createdStamp, Date createdTxStamp, String infoSession) {
		this.contactMechId = contactMechId;
		this.contactMechTypeId = contactMechTypeId;
		this.infoString = infoString;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
		this.infoSession = infoSession;
	}

	@Id

	@Column(name = "CONTACT_MECH_ID", unique = true, nullable = false, length = 20)
	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	@Column(name = "CONTACT_MECH_TYPE_ID", length = 20)
	public String getContactMechTypeId() {
		return this.contactMechTypeId;
	}

	public void setContactMechTypeId(String contactMechTypeId) {
		this.contactMechTypeId = contactMechTypeId;
	}

	@Column(name = "INFO_STRING")
	public String getInfoString() {
		return this.infoString;
	}

	public void setInfoString(String infoString) {
		this.infoString = infoString;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

	@Column(name = "info_session")
	public String getInfoSession() {
		return this.infoSession;
	}

	public void setInfoSession(String infoSession) {
		this.infoSession = infoSession;
	}

}
