package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactListPartyId generated by hbm2java
 */
@Embeddable
public class ContactListPartyId implements java.io.Serializable {

	private String contactListId;
	private String partyId;
	private Date fromDate;

	public ContactListPartyId() {
	}

	public ContactListPartyId(String contactListId, String partyId, Date fromDate) {
		this.contactListId = contactListId;
		this.partyId = partyId;
		this.fromDate = fromDate;
	}

	@Column(name = "CONTACT_LIST_ID", nullable = false, length = 20)
	public String getContactListId() {
		return this.contactListId;
	}

	public void setContactListId(String contactListId) {
		this.contactListId = contactListId;
	}

	@Column(name = "PARTY_ID", nullable = false, length = 20)
	public String getPartyId() {
		return this.partyId;
	}

	public void setPartyId(String partyId) {
		this.partyId = partyId;
	}

	@Column(name = "FROM_DATE", nullable = false, length = 19)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactListPartyId))
			return false;
		ContactListPartyId castOther = (ContactListPartyId) other;

		return ((this.getContactListId() == castOther.getContactListId())
				|| (this.getContactListId() != null && castOther.getContactListId() != null
						&& this.getContactListId().equals(castOther.getContactListId())))
				&& ((this.getPartyId() == castOther.getPartyId()) || (this.getPartyId() != null
						&& castOther.getPartyId() != null && this.getPartyId().equals(castOther.getPartyId())))
				&& ((this.getFromDate() == castOther.getFromDate()) || (this.getFromDate() != null
						&& castOther.getFromDate() != null && this.getFromDate().equals(castOther.getFromDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContactListId() == null ? 0 : this.getContactListId().hashCode());
		result = 37 * result + (getPartyId() == null ? 0 : this.getPartyId().hashCode());
		result = 37 * result + (getFromDate() == null ? 0 : this.getFromDate().hashCode());
		return result;
	}

}
