package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactMechTypePurposeId generated by hbm2java
 */
@Embeddable
public class ContactMechTypePurposeId implements java.io.Serializable {

	private String contactMechTypeId;
	private String contactMechPurposeTypeId;

	public ContactMechTypePurposeId() {
	}

	public ContactMechTypePurposeId(String contactMechTypeId, String contactMechPurposeTypeId) {
		this.contactMechTypeId = contactMechTypeId;
		this.contactMechPurposeTypeId = contactMechPurposeTypeId;
	}

	@Column(name = "CONTACT_MECH_TYPE_ID", nullable = false, length = 20)
	public String getContactMechTypeId() {
		return this.contactMechTypeId;
	}

	public void setContactMechTypeId(String contactMechTypeId) {
		this.contactMechTypeId = contactMechTypeId;
	}

	@Column(name = "CONTACT_MECH_PURPOSE_TYPE_ID", nullable = false, length = 20)
	public String getContactMechPurposeTypeId() {
		return this.contactMechPurposeTypeId;
	}

	public void setContactMechPurposeTypeId(String contactMechPurposeTypeId) {
		this.contactMechPurposeTypeId = contactMechPurposeTypeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactMechTypePurposeId))
			return false;
		ContactMechTypePurposeId castOther = (ContactMechTypePurposeId) other;

		return ((this.getContactMechTypeId() == castOther.getContactMechTypeId())
				|| (this.getContactMechTypeId() != null && castOther.getContactMechTypeId() != null
						&& this.getContactMechTypeId().equals(castOther.getContactMechTypeId())))
				&& ((this.getContactMechPurposeTypeId() == castOther.getContactMechPurposeTypeId())
						|| (this.getContactMechPurposeTypeId() != null
								&& castOther.getContactMechPurposeTypeId() != null
								&& this.getContactMechPurposeTypeId().equals(castOther.getContactMechPurposeTypeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContactMechTypeId() == null ? 0 : this.getContactMechTypeId().hashCode());
		result = 37 * result
				+ (getContactMechPurposeTypeId() == null ? 0 : this.getContactMechPurposeTypeId().hashCode());
		return result;
	}

}
