package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactMechAttributeId generated by hbm2java
 */
@Embeddable
public class ContactMechAttributeId implements java.io.Serializable {

	private String contactMechId;
	private String attrName;

	public ContactMechAttributeId() {
	}

	public ContactMechAttributeId(String contactMechId, String attrName) {
		this.contactMechId = contactMechId;
		this.attrName = attrName;
	}

	@Column(name = "CONTACT_MECH_ID", nullable = false, length = 20)
	public String getContactMechId() {
		return this.contactMechId;
	}

	public void setContactMechId(String contactMechId) {
		this.contactMechId = contactMechId;
	}

	@Column(name = "ATTR_NAME", nullable = false, length = 60)
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactMechAttributeId))
			return false;
		ContactMechAttributeId castOther = (ContactMechAttributeId) other;

		return ((this.getContactMechId() == castOther.getContactMechId())
				|| (this.getContactMechId() != null && castOther.getContactMechId() != null
						&& this.getContactMechId().equals(castOther.getContactMechId())))
				&& ((this.getAttrName() == castOther.getAttrName()) || (this.getAttrName() != null
						&& castOther.getAttrName() != null && this.getAttrName().equals(castOther.getAttrName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getContactMechId() == null ? 0 : this.getContactMechId().hashCode());
		result = 37 * result + (getAttrName() == null ? 0 : this.getAttrName().hashCode());
		return result;
	}

}
