package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactList generated by hbm2java
 */
@Entity
@Table(name = "CONTACT_LIST", catalog = "ofbiz")
public class ContactList implements java.io.Serializable {

	private String contactListId;
	private String contactListTypeId;
	private String contactMechTypeId;
	private String marketingCampaignId;
	private String contactListName;
	private String description;
	private String comments;
	private Character isPublic;
	private Character singleUse;
	private String ownerPartyId;
	private String verifyEmailFrom;
	private String verifyEmailScreen;
	private String verifyEmailSubject;
	private String verifyEmailWebSiteId;
	private String optOutScreen;
	private String createdByUserLogin;
	private String lastModifiedByUserLogin;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public ContactList() {
	}

	public ContactList(String contactListId) {
		this.contactListId = contactListId;
	}

	public ContactList(String contactListId, String contactListTypeId, String contactMechTypeId,
			String marketingCampaignId, String contactListName, String description, String comments, Character isPublic,
			Character singleUse, String ownerPartyId, String verifyEmailFrom, String verifyEmailScreen,
			String verifyEmailSubject, String verifyEmailWebSiteId, String optOutScreen, String createdByUserLogin,
			String lastModifiedByUserLogin, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.contactListId = contactListId;
		this.contactListTypeId = contactListTypeId;
		this.contactMechTypeId = contactMechTypeId;
		this.marketingCampaignId = marketingCampaignId;
		this.contactListName = contactListName;
		this.description = description;
		this.comments = comments;
		this.isPublic = isPublic;
		this.singleUse = singleUse;
		this.ownerPartyId = ownerPartyId;
		this.verifyEmailFrom = verifyEmailFrom;
		this.verifyEmailScreen = verifyEmailScreen;
		this.verifyEmailSubject = verifyEmailSubject;
		this.verifyEmailWebSiteId = verifyEmailWebSiteId;
		this.optOutScreen = optOutScreen;
		this.createdByUserLogin = createdByUserLogin;
		this.lastModifiedByUserLogin = lastModifiedByUserLogin;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@Id

	@Column(name = "CONTACT_LIST_ID", unique = true, nullable = false, length = 20)
	public String getContactListId() {
		return this.contactListId;
	}

	public void setContactListId(String contactListId) {
		this.contactListId = contactListId;
	}

	@Column(name = "CONTACT_LIST_TYPE_ID", length = 20)
	public String getContactListTypeId() {
		return this.contactListTypeId;
	}

	public void setContactListTypeId(String contactListTypeId) {
		this.contactListTypeId = contactListTypeId;
	}

	@Column(name = "CONTACT_MECH_TYPE_ID", length = 20)
	public String getContactMechTypeId() {
		return this.contactMechTypeId;
	}

	public void setContactMechTypeId(String contactMechTypeId) {
		this.contactMechTypeId = contactMechTypeId;
	}

	@Column(name = "MARKETING_CAMPAIGN_ID", length = 20)
	public String getMarketingCampaignId() {
		return this.marketingCampaignId;
	}

	public void setMarketingCampaignId(String marketingCampaignId) {
		this.marketingCampaignId = marketingCampaignId;
	}

	@Column(name = "CONTACT_LIST_NAME", length = 100)
	public String getContactListName() {
		return this.contactListName;
	}

	public void setContactListName(String contactListName) {
		this.contactListName = contactListName;
	}

	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "COMMENTS")
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "IS_PUBLIC", length = 1)
	public Character getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Character isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "SINGLE_USE", length = 1)
	public Character getSingleUse() {
		return this.singleUse;
	}

	public void setSingleUse(Character singleUse) {
		this.singleUse = singleUse;
	}

	@Column(name = "OWNER_PARTY_ID", length = 20)
	public String getOwnerPartyId() {
		return this.ownerPartyId;
	}

	public void setOwnerPartyId(String ownerPartyId) {
		this.ownerPartyId = ownerPartyId;
	}

	@Column(name = "VERIFY_EMAIL_FROM")
	public String getVerifyEmailFrom() {
		return this.verifyEmailFrom;
	}

	public void setVerifyEmailFrom(String verifyEmailFrom) {
		this.verifyEmailFrom = verifyEmailFrom;
	}

	@Column(name = "VERIFY_EMAIL_SCREEN")
	public String getVerifyEmailScreen() {
		return this.verifyEmailScreen;
	}

	public void setVerifyEmailScreen(String verifyEmailScreen) {
		this.verifyEmailScreen = verifyEmailScreen;
	}

	@Column(name = "VERIFY_EMAIL_SUBJECT")
	public String getVerifyEmailSubject() {
		return this.verifyEmailSubject;
	}

	public void setVerifyEmailSubject(String verifyEmailSubject) {
		this.verifyEmailSubject = verifyEmailSubject;
	}

	@Column(name = "VERIFY_EMAIL_WEB_SITE_ID", length = 20)
	public String getVerifyEmailWebSiteId() {
		return this.verifyEmailWebSiteId;
	}

	public void setVerifyEmailWebSiteId(String verifyEmailWebSiteId) {
		this.verifyEmailWebSiteId = verifyEmailWebSiteId;
	}

	@Column(name = "OPT_OUT_SCREEN")
	public String getOptOutScreen() {
		return this.optOutScreen;
	}

	public void setOptOutScreen(String optOutScreen) {
		this.optOutScreen = optOutScreen;
	}

	@Column(name = "CREATED_BY_USER_LOGIN", length = 250)
	public String getCreatedByUserLogin() {
		return this.createdByUserLogin;
	}

	public void setCreatedByUserLogin(String createdByUserLogin) {
		this.createdByUserLogin = createdByUserLogin;
	}

	@Column(name = "LAST_MODIFIED_BY_USER_LOGIN", length = 250)
	public String getLastModifiedByUserLogin() {
		return this.lastModifiedByUserLogin;
	}

	public void setLastModifiedByUserLogin(String lastModifiedByUserLogin) {
		this.lastModifiedByUserLogin = lastModifiedByUserLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
