package com.cornerstones.contacts.models;
// Generated Jul 1, 2017 4:29:21 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContactListPartyStatus generated by hbm2java
 */
@Entity
@Table(name = "CONTACT_LIST_PARTY_STATUS", catalog = "ofbiz")
public class ContactListPartyStatus implements java.io.Serializable {

	private ContactListPartyStatusId id;
	private String statusId;
	private String setByUserLoginId;
	private String optInVerifyCode;
	private Date lastUpdatedStamp;
	private Date lastUpdatedTxStamp;
	private Date createdStamp;
	private Date createdTxStamp;

	public ContactListPartyStatus() {
	}

	public ContactListPartyStatus(ContactListPartyStatusId id) {
		this.id = id;
	}

	public ContactListPartyStatus(ContactListPartyStatusId id, String statusId, String setByUserLoginId,
			String optInVerifyCode, Date lastUpdatedStamp, Date lastUpdatedTxStamp, Date createdStamp,
			Date createdTxStamp) {
		this.id = id;
		this.statusId = statusId;
		this.setByUserLoginId = setByUserLoginId;
		this.optInVerifyCode = optInVerifyCode;
		this.lastUpdatedStamp = lastUpdatedStamp;
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
		this.createdStamp = createdStamp;
		this.createdTxStamp = createdTxStamp;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "contactListId", column = @Column(name = "CONTACT_LIST_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "partyId", column = @Column(name = "PARTY_ID", nullable = false, length = 20) ),
			@AttributeOverride(name = "fromDate", column = @Column(name = "FROM_DATE", nullable = false, length = 19) ),
			@AttributeOverride(name = "statusDate", column = @Column(name = "STATUS_DATE", nullable = false, length = 19) ) })
	public ContactListPartyStatusId getId() {
		return this.id;
	}

	public void setId(ContactListPartyStatusId id) {
		this.id = id;
	}

	@Column(name = "STATUS_ID", length = 20)
	public String getStatusId() {
		return this.statusId;
	}

	public void setStatusId(String statusId) {
		this.statusId = statusId;
	}

	@Column(name = "SET_BY_USER_LOGIN_ID")
	public String getSetByUserLoginId() {
		return this.setByUserLoginId;
	}

	public void setSetByUserLoginId(String setByUserLoginId) {
		this.setByUserLoginId = setByUserLoginId;
	}

	@Column(name = "OPT_IN_VERIFY_CODE", length = 60)
	public String getOptInVerifyCode() {
		return this.optInVerifyCode;
	}

	public void setOptInVerifyCode(String optInVerifyCode) {
		this.optInVerifyCode = optInVerifyCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_STAMP", length = 19)
	public Date getLastUpdatedStamp() {
		return this.lastUpdatedStamp;
	}

	public void setLastUpdatedStamp(Date lastUpdatedStamp) {
		this.lastUpdatedStamp = lastUpdatedStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_UPDATED_TX_STAMP", length = 19)
	public Date getLastUpdatedTxStamp() {
		return this.lastUpdatedTxStamp;
	}

	public void setLastUpdatedTxStamp(Date lastUpdatedTxStamp) {
		this.lastUpdatedTxStamp = lastUpdatedTxStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_STAMP", length = 19)
	public Date getCreatedStamp() {
		return this.createdStamp;
	}

	public void setCreatedStamp(Date createdStamp) {
		this.createdStamp = createdStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_TX_STAMP", length = 19)
	public Date getCreatedTxStamp() {
		return this.createdTxStamp;
	}

	public void setCreatedTxStamp(Date createdTxStamp) {
		this.createdTxStamp = createdTxStamp;
	}

}
